const trainingActionableReviews = [
  "Please add a dark mode for nighttime use.",
  "Can you include a currency converter for travelers?",
  "Add a barcode scanner for price comparisons.",
  "It needs custom task reminders.",
  "Include offline translation support.",
  "We need severe weather alerts.",
  "Add meal planning functionality.",
  "More guided meditation options, please.",
  "A BMI calculator would be great.",
  "Pronunciation practice is needed.",
  "I'd love a widget for my home screen.",
  "Add investment tracking.",
  "Improve handwriting recognition.",
  "Schedule downloads during off-peak hours.",
  "Customizable news categories, please.",
  "Include safety ratings for drivers.",
  "A red-eye correction feature would be helpful.",
  "We need a dark mode for night reading.",
  "Expense prediction feature, please.",
  "Smartwatch integration is a must.",
  "Currency exchange rate calculator is needed.",
  "Pet breed identifier would be handy.",
  "Offline support is a must.",
  "A 'do not disturb' mode is needed.",
  "Progress tracking feature, please.",
  "Pollen forecast for allergies.",
  "Natural language event entry, please.",
  "Text-to-speech feature would be great.",
  "Tax calculation tools, please.",
  "Body measurement tracker is needed.",
  "Fare calculator would be helpful.",
  "Offline map download option is needed.",
  "Meal planning calendar, please.",
  "Sleep timer feature is needed.",
  "Daily email digest would be helpful.",
  "Daily affirmation feature, please.",
  "Medication reminder is needed.",
  "Live conversation practice, please.",
  "More detailed expense categories, please.",
  "Collapsible sections for better organization.",
  "We need better font customization options.",
  "A search feature within notes is needed.",
  "Allow batch editing of tasks.",
  "I want a home screen widget for quick access.",
  "Night mode for easier reading at night.",
  "Please add a filter to block spam calls.",
  "Include a step-by-step recipe mode.",
  "We need real-time stock market updates.",
  "I want a whiteboard feature for brainstorming.",
  "Please add voice memos to the app.",
  "Allow us to export notes to PDF.",
  "I want a dark mode for prolonged reading.",
  "We need a better offline mode.",
  "I want a food journal for tracking meals.",
  "Add a sleep tracking feature.",
  "Please include more font options.",
  "Allow users to sync multiple calendars.",
  "I want a word count feature for essays.",
  "Include an audio pronunciation guide.",
  "Please add custom notification sounds.",
  "Improve in-app navigation.",
  "I want a timer feature for productivity.",
  "Allow us to pin favorite recipes.",
  "I want a night mode for late-night browsing.",
  "We need a bill-splitting calculator.",
  "Include a noise-canceling option.",
  "Please add document scanning.",
  "I want a spell checker for text input.",
  "Allow us to schedule social posts.",
  "I want a password generator for security.",
  "We need a more extensive dictionary.",
  "I want a dark theme for OLED displays.",
  "Please add biometric login support.",
  "Include a customizable home screen.",
  "I want a better algorithm for news suggestions.",
  "We need a workout timer.",
  "I want a currency converter with real-time rates.",
  "Please add automatic cloud backup.",
  "Include a travel expense tracker.",
  "I want a location-based reminders feature.",
  "We need custom email folders.",
  "I want a better widget for weather updates.",
  "Please add collaborative document editing.",
  "Include multi-language support.",
  "I want a built-in podcast transcriber.",
  "We need an integrated note-taking tool.",
  "I want a faster image upload feature.",
  "Please add multi-window support.",
  "Include a group video chat feature.",
  "I want a smart shopping list with suggestions.",
  "We need a passcode lock for privacy.",
  "I want a more robust color palette.",
  "Please add a progress tracking widget.",
  "Include a smart assistant feature.",
  "I want a reverse image search option.",
  "We need better background audio playback.",
  "I want a unified inbox for messages.",
  "Please add a call recording feature.",
  "Include a public transport route planner.",
  "I want a currency exchange rate widget.",
  "We need a better QR code scanner.",
  "I want a family sharing plan for subscriptions.",
  "Please add a quick settings menu.",
  "Include a customizable widget maker.",
  "I want a cross-platform collaboration tool.",
  "We need offline map caching.",
  "I want a detailed weekly weather forecast.",
  "Please add a handwriting recognition feature.",
  "Include a task completion widget.",
  "I want a better offline reading mode.",
  "We need a personalized news feed.",
  "I want a visual voicemail feature.",
  "Please add a conference call scheduler.",
  "Include a quick reply feature.",
  "I want a more extensive font library.",
  "We need better organization of saved articles.",
  "I want a built-in currency converter.",
  "Please add a barcode scanner for product info.",
  "Include a QR code generator.",
  "I want a shared calendar for family events.",
  "We need a contact sync feature.",
  "I want a better folder organization system.",
  "Please add a 'read later' button.",
  "Include a document scanner.",
  "I want a voice assistant integration.",
  "We need an option to hide read messages.",
  "I want a built-in news reader.",
  "Please add a currency exchange rate calculator.",
  "Include a location-based reminders widget.",
  "I want a photo slideshow feature.",
  "We need a home screen sticky note widget.",
  "I want a more intuitive voice search.",
  "Please add a built-in weather radar.",
  "Include a recipe import feature.",
  "I want a better document editor.",
  "We need a night mode for camera use.",
  "I want a customizable workout routine builder.",
  "Please add an integrated time tracker.",
  "Include a document signature feature.",
  "I want a secure private browsing mode.",
  "We need a calorie tracking widget.",
  "I want a better stock market news section.",
  "Please add offline GPS navigation.",
  "Include a password vault.",
  "I want a customizable home screen clock widget.",
  "We need a password strength meter.",
  "I want a bulk delete option for emails.",
  "Please add a countdown timer widget.",
  "Include a document annotation tool.",
  "I want a sleep tracking widget for the home screen.",
  "We need a workout history log.",
  "I want a better image cropping tool.",
  "Please add a text-to-speech widget.",
  "Include a meal planner widget.",
  "I want a voice memo widget for quick notes.",
  "We need a better workout routine builder.",
  "I want a built-in note-taking widget.",
  "Please add a calorie counter widget.",
  "Include a real-time traffic widget.",
  "I want a customizable widget for news updates.",
  "We need a meal recommendation feature.",
  "I want a better calendar event search function.",
  "Please add a shopping list widget.",
  "Include a currency exchange rate widget.",
  "I want a customizable fitness goal widget.",
  "We need a document scanner widget.",
  "I want a meal preparation planner.",
  "Please add a news ticker widget.",
  "Include a customizable workout timer widget.",
  "I want a task checklist widget for the home screen.",
  "We need a currency conversion widget.",
  "I want a medication reminder widget.",
  "Please add a budget tracker widget.",
  "Include a weather radar widget.",
  "I want a recipe of the day widget.",
  "We need a customizable home screen widget.",
  "I want a customizable clock widget.",
  "Please add a goal tracker widget.",
  "Include a countdown timer widget.",
  "I want a shopping list widget with voice input.",
  "I want a budget tracker widget with expense charts.",
  "Please add a note-taking widget.",
  "I want a weather forecast widget with UV index.",
  "We need a meal planner widget.",
  "I want a customizable habit tracker widget.",
  "Please add a currency exchange rate widget.",
  "Include a news headline ticker widget.",
  "I want a customizable workout routine widget.",
  "We need a document signature widget.",
  "I want a sleep tracking widget with sleep stages.",
  "Please add a calendar event widget.",
  "Include a medication reminder widget.",
  "I want a budget tracker widget with expense breakdown.",
  "We need a weather radar widget.",
  "I want a recipe of the day widget with nutritional info.",
  "Please add a customizable news widget.",
  "Include a currency conversion widget.",
  "I want a meal preparation planner widget.",
  "We need a task checklist widget.",
  "I want a real-time traffic widget with alternate routes.",
  "Include a voice memo widget.",
  "I want a currency exchange rate widget with live rates.",
  "We need a note-taking widget with handwriting recognition.",
  "I want a weather forecast widget with pollen count.",
  "Please add a customizable habit tracker widget.",
  "Include a document scanner widget with OCR.",
  "I want a customizable workout routine widget with progress tracking.",
  "We need a medication reminder widget with refill alerts.",
  "I want a budget tracker widget with bill due dates.",
  "Please add a currency exchange rate widget with historical data.",
  "Include a news headline ticker widget with customizable sources.",
  "I want a customizable meal preparation planner widget.",
  "We need a task checklist widget with subtasks.",
  "I want a real-time traffic widget with accident notifications.",
  "Please add a countdown timer widget with interval settings.",
  "Include a voice memo widget with transcription.",
  "I want a currency exchange rate widget with conversion history.",
  "We need a note-taking widget with voice input.",
  "I want a weather forecast widget with severe weather alerts.",
  "Please add a customizable habit tracker widget with streaks.",
  "Include a document scanner widget with cloud storage integration.",
  "I want a customizable workout routine widget with workout history.",
  "We need a medication reminder widget with dosage instructions.",
  "I want a budget tracker widget with expense category breakdown.",
  "Please add a currency exchange rate widget with cryptocurrency support.",
  "Include a news headline ticker widget with news category filters.",
  "I want a customizable meal preparation planner widget with dietary restrictions.",
  "We need a task checklist widget with recurring task options.",
  "I want a real-time traffic widget with live camera feeds.",
  "Please add a countdown timer widget with voice commands.",
  "Include a voice memo widget with automatic transcription.",
  "I want a currency exchange rate widget with offline conversion.",
  "We need a note-taking widget with cross-device syncing.",
  "I want a weather forecast widget with air quality index.",
  "Please add a customizable habit tracker widget with goal setting.",
  "Include a document scanner widget with advanced editing tools.",
  "I want a customizable workout routine widget with workout statistics.",
  "We need a medication reminder widget with medication images.",
  "I want a budget tracker widget with monthly budget summaries.",
  "Please add a currency exchange rate widget with historical trends.",
  "Include a news headline ticker widget with language selection.",
  "I want a customizable meal preparation planner widget with grocery list.",
  "We need a task checklist widget with task dependencies.",
  "I want a real-time traffic widget with parking availability info.",
  "Please add a countdown timer widget with multiple timers.",
  "Include a voice memo widget with voice recognition.",
  "I want a currency exchange rate widget with automatic rate updates.",
  "We need a note-taking widget with cloud backup.",
  "I want a weather forecast widget with sunrise and sunset times.",
  "Please add a customizable habit tracker widget with habit streaks.",
  "Include a document scanner widget with text extraction.",
  "I want a customizable workout routine widget with goal tracking.",
  "We need a medication reminder widget with refill history.",
  "I want a budget tracker widget with expense prediction.",
  "Please add a currency exchange rate widget with historical graphs.",
  "Include a news headline ticker widget with location-based news.",
  "I want a customizable meal preparation planner widget with recipe suggestions.",
  "We need a task checklist widget with task priority settings.",
  "I want a real-time traffic widget with real-time traffic camera feeds.",
  "Please add a countdown timer widget with custom alarm sounds.",
  "Include a voice memo widget with language translation.",
  "I want a currency exchange rate widget with cryptocurrency conversion.",
  "We need a note-taking widget with offline access.",
  "I want a weather forecast widget with weather alerts.",
  "Please add a customizable habit tracker widget with habit notes.",
  "Include a document scanner widget with document signing.",
  "I want a customizable workout routine widget with progress charts.",
  "We need a medication reminder widget with medication interaction warnings.",
  "I want a budget tracker widget with expense analysis.",
  "Please add a currency exchange rate widget with currency exchange history.",
  "Include a news headline ticker widget with keyword filters.",
  "I want a customizable meal preparation planner widget with meal recommendations.",
  "We need a task checklist widget with task notes.",
  "I want a real-time traffic widget with live traffic incident reports.",
  "Please add a countdown timer widget with timer presets.",
  "Include a voice memo widget with language transcription.",
  "I want a currency exchange rate widget with automatic currency updates.",
  "We need a note-taking widget with document synchronization.",
  "I want a weather forecast widget with real-time weather data.",
  "Please add a customizable habit tracker widget with habit analytics.",
  "Include a document scanner widget with document categorization.",
  "I want a customizable workout routine widget with workout achievements.",
  "We need a medication reminder widget with medication side effect warnings.",
  "I want a budget tracker widget with expense projection.",
  "Please add a currency exchange rate widget with currency trend analysis.",
  "Include a news headline ticker widget with personalized news recommendations.",
  "I want a customizable meal preparation planner widget with meal planning templates.",
  "We need a task checklist widget with task completion statistics.",
  "I want a real-time traffic widget with traffic camera snapshots.",
  "Please add a countdown timer widget with countdown animation.",
  "Include a voice memo widget with voice-to-text translation.",
  "I want a currency exchange rate widget with automatic currency rate alerts.",
  "We need a note-taking widget with document version history.",
  "I want a weather forecast widget with weather radar.",
  "Please add a customizable habit tracker widget with habit streak analytics.",
  "Include a document scanner widget with document annotation.",
  "I want a customizable workout routine widget with workout history analysis.",
  "We need a medication reminder widget with medication dosage reminders.",
  "I want a budget tracker widget with expense trend analysis.",
  "Please add a currency exchange rate widget with real-time currency news.",
  "Include a news headline ticker widget with real-time news updates.",
  "I want a customizable meal preparation planner widget with meal planning calendar.",
  "We need a task checklist widget with task priority reminders.",
  "I want a real-time traffic widget with live traffic camera videos.",
  "Please add a countdown timer widget with custom countdown themes.",
  "Include a voice memo widget with voice memo transcription.",
  "I want a currency exchange rate widget with currency converter widgets.",
  "We need a note-taking widget with voice memo synchronization.",
  "I want a weather forecast widget with hurricane tracking.",
  "Please add a customizable habit tracker widget with habit trend charts.",
  "Include a document scanner widget with document scanning presets.",
  "I want a customizable workout routine widget with workout plan templates.",
  "We need a medication reminder widget with medication refill notifications.",
  "I want a budget tracker widget with expense category trends.",
  "Please add a currency exchange rate widget with currency rate prediction.",
  "Include a news headline ticker widget with customizable news sources.",
  "The app constantly crashes when I try to open the settings menu.",
  "Why does this app require so many unnecessary permissions?",
  "The new update ruined the user interface; it's now confusing to navigate.",
  "Notifications are so annoying; I can't turn them off completely.",
  "This app drains my battery like crazy, even when it's not in use.",
  "The chat feature is buggy; messages often get delayed or don't send at all.",
  "I hate the new color scheme; it's hard to read in bright light.",
  "The ads are way too intrusive; they pop up every few seconds.",
  "The search function rarely returns accurate results; it's frustrating.",
  "Why can't I customize the app's layout to my liking?",
  "The customer support is non-existent; no one ever responds to my inquiries.",
  "The app crashes every time I try to upload a photo.",
  "The recent update made the app slower and more laggy.",
  "The app keeps asking for my location even when it's not needed.",
  "I can't believe they removed the feature I used most often.",
  "This app constantly freezes, making it impossible to use.",
  "The ads in the middle of videos are incredibly disruptive.",
  "The app drains my data plan; it's constantly syncing in the background.",
  "The in-app purchases are ridiculously expensive; it's a money grab.",
  "The app is full of spelling and grammar errors; it's unprofessional.",
  "Why can't I use this app in landscape mode on my tablet?",
  "The app logs me out randomly, and I have to log in repeatedly.",
  "The app's voice recognition is terrible; it never understands me.",
  "The app's font size is too small, and there's no way to adjust it.",
  "This app's support for older devices is terrible; it's almost unusable.",
  "The app doesn't support multitasking on my iPad; it's frustrating.",
  "The app's interface is cluttered and confusing; it needs a redesign.",
  "The app crashes when I try to send voice messages.",
  "The constant updates are annoying; they never seem to fix anything.",
  "The app drains my phone's storage with unnecessary cache files.",
  "The app's privacy settings are confusing and hard to find.",
  "The app's search function is so slow; it takes forever to load results.",
  "The ads are inappropriate and not suitable for all ages.",
  "Why do I have to create an account just to use this app?",
  "The app's offline mode is unreliable; it often fails to load content.",
  "The app's video player is buggy; videos often freeze or stutter.",
  "The app's notifications are delayed; I miss important messages.",
  "The app keeps asking for a rating every time I open it.",
  "The app's login process is tedious and time-consuming.",
  "The app's permissions are invasive; it collects too much personal data.",
  "The app constantly nags me to invite friends; it's annoying.",
  "The app's updates always seem to make it worse, not better.",
  "The app's location accuracy is terrible; it often shows the wrong place.",
  "The app's notifications are redundant; I get the same alert multiple times.",
  "The app's user interface is outdated and needs a modern overhaul.",
  "The app's error messages are unhelpful and cryptic.",
  "The app's layout is not intuitive; it's hard to find what I need.",
  "The app's font choices are terrible; it's hard to read text.",
  "The app's tutorial is uninformative; it doesn't explain how to use it.",
  "The app's image compression ruins the quality of photos.",
  "The app's customer service is slow to respond and unhelpful.",
  "The app's sign-up process requires too much personal information.",
  "The app's notifications are invasive and can't be customized.",
  "The app's loading times are excruciatingly slow; it's frustrating.",
  "The app's ads are often misleading and deceptive.",
  "The app's notification sounds are annoying and can't be changed.",
  "The app's password reset process is overly complicated.",
  "The app's location tracking is creepy and invasive.",
  "The app's photo upload feature always fails; it's unreliable.",
  "The app's notification badges are glitchy and don't clear correctly.",
  "The app's push notifications are obnoxious and intrusive.",
  "The app's data usage is excessive, even on Wi-Fi.",
  "The app's search algorithm is terrible; it can't find what I want.",
  "The app's recent update deleted all my saved data; it's frustrating.",
  "The app's user interface is not user-friendly at all.",
  "The app's constant requests for reviews are annoying.",
  "The app's login process is slow and prone to errors.",
  "The app's location-based ads are irrelevant and annoying.",
  "The app's settings menu is cluttered and hard to navigate.",
  "The app's chat notifications are unreliable; I miss messages.",
  "The app's video quality is terrible; it's pixelated and blurry.",
  "The app's constant requests for access to my contacts are invasive.",
  "The app's font size is too large, and there's no way to change it.",
  "The app's photo editor is limited and lacks essential features.",
  "The app's in-app purchases are overpriced and not worth it.",
  "The app's layout is not customizable; it's frustrating.",
  "The app's frequent crashes make it unusable.",
  "The app's constant notifications about new features are annoying.",
  "The app's search function is unreliable; it often returns no results.",
  "The app's ads are too frequent and disrupt my experience.",
  "The app's offline mode doesn't work at all; it's useless.",
  "The app's permissions request is excessive and invasive.",
  "The app's login process is complicated and confusing.",
  "The app's location-based features drain my battery quickly.",
  "The app's video player is clunky and lacks basic features.",
  "The app's notifications are intrusive and can't be disabled.",
  "The app's updates always seem to introduce new bugs.",
  "The app's font choice is hard to read; it needs improvement.",
  "The app's error messages are unhelpful and frustrating.",
  "The app's sign-up process is overly complicated.",
  "The app's location tracking is invasive and creepy.",
  "The app's photo upload feature is slow and unreliable.",
  "The app's voice recognition feature often misunderstands my commands.",
  "The constant app updates are frustrating, and they never seem to fix anything.",
  "Why does this app use so much background data even when not in use?",
  "The app's video streaming quality is terrible; it buffers every few seconds.",
  "The app's new UI overhaul is confusing; it's a step backward.",
  "I can't believe this app still lacks a dark mode option.",
  "The app's lack of multi-device syncing is a major inconvenience.",
  "The constant banner ads at the bottom of the screen are distracting.",
  "The app's new privacy policy is invasive; it asks for too much personal information.",
  "This app's notification spam is out of control; I'm bombarded with alerts.",
  "The app's GPS accuracy is off, and it often gives incorrect directions.",
  "The app's constant push for premium subscriptions is annoying.",
  "Why can't I customize the app's notification sounds?",
  "The app's image compression feature seriously degrades photo quality.",
  "The app's customer support takes ages to respond to inquiries.",
  "The app's frequent pop-up ads make it nearly unusable.",
  "The app's login process is overly complicated and prone to errors.",
  "The app's constant requests for location access are intrusive.",
  "The new update made the app's interface cluttered and hard to navigate.",
  "The app's font choices are outdated and make reading difficult.",
  "The app's constant crashes when playing games are frustrating.",
  "Why is there no option to export data or back it up?",
  "The app's lack of landscape mode on tablets is disappointing.",
  "The app's constant loading screens and lag make it painful to use.",
  "The app's search function is slow, and the results are often irrelevant.",
  "This app's battery usage is excessive; it's a power hog.",
  "The app's intrusive ads often lead to accidental clicks.",
  "The app's frequent network errors make it unreliable.",
  "The app's offline mode doesn't work reliably; it often fails to load content.",
  "The app's constant requests to rate it are obnoxious.",
  "The app's recent redesign removed features I relied on; it's frustrating.",
  "The app's data syncing between devices is unreliable.",
  "The app's notification badges are glitchy and don't clear properly.",
  "The app's constant prompts to invite friends are annoying.",
  "The app's lack of a tablet-optimized layout is disappointing.",
  "The app's font size is too small, and there's no way to increase it.",
  "The app's frequent freezes and crashes make it unbearable.",
  "The app's notification sound options are limited and boring.",
  "The app's constant updates eat up my mobile data plan.",
  "The app's lack of landscape mode on larger screens is a major oversight.",
  "The app's persistent ads for in-app purchases are irritating.",
  "The app's frequent login errors are frustrating; I have to reset my password often.",
  "The app's video player is outdated and lacks essential features.",
  "The app's frequent reminders to turn on notifications are annoying.",
  "The app's recent update deleted my saved bookmarks and history; it's infuriating.",
  "The app's photo editor lacks basic editing tools and filters.",
  "The app's in-app purchases are ridiculously expensive for what they offer.",
  "The app's layout is cluttered, and it's hard to find important settings.",
  "The app's constant crashes when trying to open PDFs are infuriating.",
  "The app's notifications often arrive out of order, making conversations confusing.",
  "The app's lack of support for older devices is disappointing.",
  "The app's persistent requests for access to my photos are invasive.",
  "The app's frequent updates are cumbersome and disrupt my workflow.",
  "The app's dark mode implementation is poorly done; it needs improvement.",
  "The app's frequent prompts to rate it are irritating and disruptive.",
  "The app's notification settings are too limited; I can't customize them to my liking.",
  "The app's lack of tablet optimization makes it unusable on larger screens.",
  "The app's font choices are bland and unattractive.",
  "The app's constant buffering during video playback is infuriating.",
  "The app's privacy policy is too lengthy and complex to understand.",
  "The app's constant push notifications to invite friends are annoying.",
  "The app's constant pop-ups asking me to upgrade to the premium version are intrusive.",
  "The app's constant prompts to enable location services are annoying.",
  "The app's video streaming quality is subpar; it often lags and stutters.",
  "The app's recent update introduced more bugs than it fixed.",
  "The app's search function rarely returns accurate results; it's frustrating.",
  "The app's frequent login issues are infuriating.",
  "The app's lack of customer support responsiveness is disappointing.",
  "The app's constant reminders to rate it are irritating.",
  "The app's constant ads for in-app purchases are annoying.",
  "The app's font size is too large, and there's no option to change it.",
  "The app's lack of compatibility with older devices is a major drawback.",
  "The app's constant prompts to enable push notifications are intrusive.",
  "The app's dark mode option is poorly implemented; it needs improvement.",
  "The app's lack of an undo feature in the text editor is frustrating.",
  "The app's notification sounds are annoying, and there's no way to customize them.",
  "The app's recent update wiped out my saved data; it's infuriating.",
  "The app's constant prompts to invite friends are disruptive.",
  "The app's layout is cluttered, and it's hard to find what I need.",
  "The app's video player often fails to load videos properly.",
  "The app's frequent prompts to rate it are annoying.",
  "The app's notifications often arrive late; it's frustrating.",
  "The app's recent redesign made it less user-friendly.",
  "The app's lack of tablet support is a major drawback.",
  "The app's font choices are outdated and make text hard to read.",
  "The app's frequent updates are disruptive and don't seem to improve performance.",
  "The app's frequent ads for in-app purchases are irritating.",
  "The app's constant pop-ups asking me to upgrade to premium are annoying.",
  "The app's constant reminders to invite friends are disruptive.",
  "The app's dark mode implementation is poorly executed; it needs improvement.",
  "The app's recent update introduced more bugs and glitches.",
  "The app's search function rarely returns relevant results; it's frustrating.",
  "The app's lack of responsive customer support is disappointing.",
  "The app's frequent ads for in-app purchases are intrusive.",
  "The app's constant prompts to enable push notifications are irritating.",
  "The app's interface is a mess, making it impossible to navigate.",
  "This app's frequent crashes are incredibly frustrating.",
  "The app's constant pop-up ads disrupt the user experience.",
  "The app's recent update removed useful features; I'm disappointed.",
  "Why does this app consume so much battery even in the background?",
  "The app's notifications are excessive and overwhelming.",
  "The app's lack of offline functionality is a major drawback.",
  "The constant requests for access to my camera are invasive.",
  "This app's lack of customer support responsiveness is frustrating.",
  "The app's constant reminders to rate it are annoying.",
  "The app's frequent permission requests are a privacy concern.",
  "The app's lack of a dark mode option is disappointing.",
  "The app's frequent prompts to invite friends are intrusive.",
  "The app's constant updates disrupt my workflow.",
  "The app's photo editing tools are rudimentary and need improvement.",
  "The app's notification sounds are obnoxious and can't be customized.",
  "The app's constant prompts to enable push notifications are annoying.",
  "The app's recent redesign made it less intuitive.",
  "This app's excessive data usage is a problem, especially on mobile data.",
  "The app's video streaming quality is subpar; it buffers too much.",
  "The app's search feature is slow and often returns irrelevant results.",
  "The app's frequent login errors are infuriating.",
  "The app's lack of a dark mode option strains my eyes at night.",
  "The app's persistent requests for location access are annoying.",
  "The app's constant requests for reviews are disruptive.",
  "The app's frequent prompts to upgrade to the premium version are irritating.",
  "The app's layout is cluttered, making it hard to find what I need.",
  "The app's frequent prompts to rate it are intrusive.",
  "The app's notifications often arrive out of order, causing confusion.",
  "The app's font size is too small, making it difficult to read.",
  "The app's constant updates introduce more bugs than they fix.",
  "The app's lack of a landscape mode on tablets is a letdown.",
  "The app's image compression feature ruins photo quality.",
  "The app's recent update caused a significant decline in performance.",
  "The app's video player lacks basic features like fast-forward and rewind.",
  "The app's lack of offline mode makes it useless without an internet connection.",
  "The app's frequent prompts to enable location services are invasive.",
  "The app's constant requests for access to my contacts are intrusive.",
  "The app's font choices are outdated and unappealing.",
  "The app's notification badges often don't clear properly.",
  "The app's constant ads for in-app purchases are irritating.",
  "The app's layout is not user-friendly; it needs a redesign.",
  "The app's constant prompts to rate it are annoying and persistent.",
  "The app's lack of customization options is limiting.",
  "The app's frequent crashes during video calls are frustrating.",
  "The app's frequent prompts to invite friends are obnoxious.",
  "The app's constant push notifications are intrusive and disruptive.",
  "The app's lack of a dark mode is a missed opportunity.",
  "The app's constant requests for reviews are annoying and relentless.",
  "The app's login process is overly complicated and confusing.",
  "The app's video quality is often pixelated and low-resolution.",
  "The app's constant requests for access to my microphone are invasive.",
  "The app's frequent login issues are a major inconvenience.",
  "The app's lack of customer support makes it difficult to resolve issues.",
  "The app's dark mode implementation is poorly executed.",
  "The app's notification sounds are jarring and can't be customized.",
  "The app's photo editing tools are basic and need improvement.",
  "The app's layout is cluttered, and it's challenging to find settings.",
  "The app's video player frequently freezes and crashes.",
  "The app's notifications often arrive late or not at all.",
  "The app's lack of tablet support is a significant drawback.",
  "The app's font choices are outdated and hard to read.",
  "The app's frequent updates disrupt my usage and introduce new bugs.",
  "The app's user interface is outdated and in need of a modern overhaul.",
  "This app's constant freezing is driving me crazy.",
  "The excessive ads in this app ruin the experience.",
  "The recent app update removed features I used daily; I'm frustrated.",
  "Why does this app drain my battery so quickly?",
  "The overwhelming number of notifications from this app is unbearable.",
  "Lack of offline access makes this app useless on the go.",
  "The app's repeated requests for camera access are invasive.",
  "In-app purchases in this app are overpriced and not justified.",
  "This app's lack of responsive customer support is disappointing.",
  "The relentless reminders to rate the app are annoying.",
  "The constant permission requests from this app are a privacy concern.",
  "Network errors in this app make it unreliable for daily use.",
  "A dark mode option in this app would be a welcome addition.",
  "This app's persistent invites for friends are intrusive.",
  "Frequent updates disrupt my workflow; it's frustrating.",
  "Photo editing tools in this app are basic; they need improvement.",
  "App notification sounds are disruptive and can't be customized.",
  "Stop asking me to enable push notifications every time I open the app!",
  "The recent redesign of this app made it less user-friendly.",
  "Excessive data usage by this app is a problem on limited plans.",
  "Video streaming quality is consistently poor; it needs enhancement.",
  "The app's search function is slow and often returns irrelevant results.",
  "Frequent login errors make using this app a nightmare.",
  "A dark mode would be a great addition to this app for night use.",
  "The constant request for location access is annoying.",
  "This app's unending requests for reviews are disruptive.",
  "Logging in to this app is a convoluted process.",
  "Location-based features drain my battery faster than anything else.",
  "Video quality in this app is often pixelated and disappointing.",
  "Stop asking for microphone access; it's invasive.",
  "Frequent login issues with this app are unacceptable.",
  "Lack of customer support makes resolving issues a challenge.",
  "The app's constant push for premium subscriptions is irritating.",
  "Relentless reminders to invite friends are disruptive.",
  "App updates seem to introduce more problems than they fix.",
  "The video player lacks basic features like fast-forward and rewind.",
  "Offline mode is a must-have; please add it to this app.",
  "Stop requesting location access; it's invasive.",
  "The constant access to my contacts is a breach of privacy.",
  "Font choices in this app are unattractive and outdated.",
  "App badges for notifications often don't clear correctly.",
  "Too many ads for in-app purchases; it's annoying.",
  "This app's layout needs a complete overhaul for better usability.",
  "Enough with the prompts to rate the app; they're persistent.",
  "Limited customization options are holding this app back.",
  "Frequent video call crashes are frustrating.",
  "Syncing data between devices in this app is unreliable.",
  "Quit asking me to invite friends to use the app; it's obnoxious.",
  "Push notifications from this app are overwhelming.",
  "A dark mode would be a significant improvement for this app.",
  "The constant demand for location access is invasive.",
  "I'm tired of being bombarded with requests for reviews from this app.",
  "This app's network errors are frustrating.",
  "The app's font size is too small; it's hard to read.",
  "Updates for this app often cause more problems than they solve.",
  "Stop asking for location services; it's annoying.",
  "Frequent ads for in-app purchases are irritating.",
  "Pop-ups urging me to upgrade to premium are frustrating.",
  "The constant reminders to invite friends are disruptive.",
  "Dark mode implementation in this app needs improvement.",
  "The recent update introduced even more glitches; it's frustrating.",
  "The search function rarely delivers relevant results; it's frustrating.",
  "The photo upload feature is slow and unreliable in this app.",
  "Frequent login issues are infuriating.",
  "The app's customer support is unresponsive; it's disappointing.",
  "This app's requests for reviews are relentless.",
  "The excessive ads for in-app purchases are intrusive.",
  "Font size in this app is too large; please provide options.",
  "This app is not compatible with older devices; it's a drawback.",
  "Push notification prompts are constantly irritating.",
  "The dark mode option needs significant improvement in this app.",
  "Frequent app crashes render it unusable.",
  "The lack of an undo feature in the text editor is frustrating.",
  "App notification sounds are annoying, and customization is needed.",
  "The recent update wiped out my saved data; it's infuriating.",
  "Image compression in this app degrades photo quality.",
  "Quit prompting me to invite friends to use the app; it's disruptive.",
  "This app's cluttered layout makes it hard to navigate.",
  "Requests for access to my contacts are invasive in this app.",
  "The video player frequently fails to load videos properly.",
  "Stop asking me to rate the app repeatedly; it's annoying.",
  "Notifications from this app often arrive late; it's frustrating.",
  "The constant requests for location access are intrusive.",
  "The recent redesign made this app less user-friendly.",
  "The app lacks support for tablets, which is a major drawback.",
  "Font choices in this app are outdated and unattractive.",
  "Frequent updates disrupt the user experience.",
  "Constant requests to enable location services are annoying.",
  "Ads for in-app purchases are frequent and annoying.",
  "Pop-ups asking to upgrade to premium are intrusive.",
  "The never-ending reminders to invite friends are disruptive.",
  "The dark mode implementation in this app needs improvement.",
  "The recent update introduced numerous bugs and glitches.",
  "The search function rarely returns relevant results; it's frustrating.",
  "The photo upload feature is slow and unreliable.",
  "The lack of responsive customer support is disappointing.",
  "Frequent ads for in-app purchases are intrusive.",
  "The app's font size is too large; there's no option to change it.",
  "Lack of compatibility with older devices is a major drawback.",
  "The dark mode option in this app is poorly implemented.",
  "Notification sounds are annoying, and customization is needed.",
  "Image compression ruins the quality of photos in this app.",
  "The app's cluttered layout makes it hard to find what I need.",
  "The video player often fails to load videos properly.",
  "Stop asking me to rate the app; it's annoying.",
  "Notifications often arrive late in this app; it's frustrating.",
  "The lack of tablet support is a significant drawback.",
  "Font choices in this app are outdated and make text hard to read.",
  "Frequent updates are disruptive and don't seem to improve performance.",
  "Constant prompts to enable location services are annoying.",
  "Pop-ups asking to upgrade to premium are annoying.",
  "Dark mode implementation in this app is poorly executed.",
  "The recent update introduced more bugs and glitches.",
  "Lack of responsive customer support is disappointing.",
  "The dark mode option is poorly implemented; it needs improvement.",
];

export default trainingActionableReviews;
